### ISSUE TITLE
Shader Error Log Size + Potential memory leaks

### ISSUE THREAD

**Issue by datavorous** [TeslaSparkz/opengl_playground#1]
The logic for getting the shader info log might be incorrect? If len is 0, it can cause an out-of-bounds error.

Also, use gl::DeleteShader, gl::DeleteVertexArrays, gl::DeleteBuffers etc for cleanup.

**Comment by TeslaSparkz** [comment]
Thanks for your valuable suggestions I will make sure to implement the changes you have mentioned for better memory safe code
